### ISSUE TITLE
Doesn't load data

### ISSUE THREAD

**Issue by LitRidl** [artzub/clearspending#2]
Version on http://clearspending.artzub.com/ worked correctly for some time, but soon stopped working.

Map picture loads, but no action is going on.
The error is "Uncaught TypeError: undefined is not a function".

**Comment by artzub** [comment]
Thank you very much!
The problem was with d3.js v3.5.5, I downgrade version to v3.5.3
into v3.5.5 d3.selection.datum returns HTMLElement, but into v3.5.3 — returns d3.selection.
Thanks a lot!

**Comment by artzub** [comment]
Thank you very much!
The problem was with d3.js v3.5.5, I downgrade version to v3.5.3
into v3.5.5 d3.selection.datum returns HTMLElement, but into v3.5.3 — returns d3.selection.
Thanks a lot!
